name: Check

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
        
      - name: Run lint
        run: yarn lint
        
      - name: Run build
        run: yarn build
